server:
  port: 8081
#指定数据库配置
spring:
  datasource:
    url: jdbc:mysql://124.204.68.210:42102/bengallis?useUnicode=true&characterEncoding=utf8
    username: bengallis
    password: Sinosoft@admin#bengallis2022
    driver-class-name: com.mysql.cj.jdbc.Driver
#要选择的具体数据库
database: bengallis